//@version=5
strategy('SC implementation', overlay=true,initial_capital = 1000,process_orders_on_close = true)
//---Logic-------------
//8+14 ema for entries
//20+50 for trend direction
//check 1h tf for overall trend and direction
//entries on 1 min


// TO DO
// create crossover Alerts with his indicator
//create price crossover alerts
// have little label near price indicating direction of trend based on crossover



//------------------
//plot triangle on crossovers
//hide the 8 and 14 ema, only use to cal plotting arrow
//---Backend----------------------------
//EMA---------------------
EMAsetting=input.int(300, "EMA setting", minval=1)
Highertimeframe="15"

ema8=ta.ema(close, 8)
ema14=ta.ema(close, 14)
ema20=ta.ema(close, 20)
ema50=ta.ema(close, 50)
htfTrend=request.security(syminfo.tickerid, Highertimeframe,ta.ema(close, EMAsetting))

//Conditions ------------------
isUp=ema20>ema50
isDown=ema20<ema50

// plot(ema8, color=color.green)
// plot(ema14, color=color.purple)
crossover = ta.crossover(ema8, ema14)
crossunder = ta.crossunder(ema8, ema14)
plotshape(crossover, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny) //color.rgb(255, 220, 64)
plotshape(crossunder, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny)
plotshape(ta.crossover(ema20, ema50), style=shape.triangleup, location=location.belowbar, color=color.rgb(255, 220, 64), size=size.small)
plotshape(ta.crossunder(ema20, ema50), style=shape.triangledown, location=location.abovebar, color=color.rgb(255, 220, 64), size=size.small)
plot(ema20, color=color.aqua)
plot(ema50, color=color.orange)
//plot(htfTrend, color=color.white)

//---Conditions----------------------------

trend=0
if (isUp)
    trend:=1
else if (isDown)
    trend:=-1
else
    trend:=0

//Alerts ------------------
alertcondition(crossover, title="Long entry", message="8 + 14 ema crossover")
alertcondition(crossunder, title="Short entry", message="8 + 14 ema crossover")
alertcondition(ta.crossover(ema20, ema50), title="Long entry", message="20 + 50 ema crossover")
alertcondition(ta.crossunder(ema20, ema50), title="Short entry", message="20 + 50 ema crossover")

alertcondition(close>ema20, title="Price crossed the 20 ema", message="Price cross 20 ema")
alertcondition(close>ema20, title="Price crossed the 50 ema", message="Price cross 50 ema")
//---BG coloring-------------------------------------
bgcolor(color= trend==1 ? color.rgb(76, 175, 79, 95): trend==-1 ? color.rgb(255, 82, 82, 95): trend==0 ? color.rgb(0, 0, 0, 50) : na)

// //---Exit----------------------------
// if (BuyExitSignal and strategy.position_size > 0) // close if long
//     strategy.close_all()
// if (SellExitSignal and strategy.position_size < 0) // close if short
//     strategy.close_all()

// //---Long----------------------------
// if (BuySignal and trend==1)
//     strategy.entry('LONG', strategy.long)

// //---Short----------------------------
// if (SellSignal and trend==-1)
//     strategy.entry('SHORT', strategy.short)
